### ISSUE TITLE
Differentiating types of Google locations

### ISSUE THREAD

**Issue by lucix-mich** [stevesong/cloud_cdn_cache#1]
Hello,

Very useful work, thanks a lot for that!

For Google I would however suggest to use the list of Google cache locations, since your map targets CDN locations. Currently you are mapping Google edge locations, i.e. those that allow access to Google Cloud.
Google's caches can be found here: https://cloud.google.com/cdn/docs/locations

Thanks and cheers

**Comment by lucix-mich** [comment]
Argh.... and the link I gave is still not the right one for CDN... the locations are visible on this map:
https://peering.google.com/#/infrastructure
What you want to look at is GGC (Google Global Cache).

**Comment by stevesong** [comment]
Thanks!  Google seem to want to  deliberately discourage any detailed exploration of their GGCs.  In theory I could have brute forced their GGC map (as I did with Akamai) but they have disabled zooming on their GGC map.  Open to other suggestions.

**Comment by stevesong** [comment]
I have found a different data source for Google and now, when you mouseover a node, you can tell whether it is a Google Datacentre, PoP, or GGC.

**Comment by lucix-mich** [comment]
Cool, thanks!
